// frontend/src/pages/MyPermissions/index.tsx
import {
    Table,
    TableBody,
    TableCell,
    TableContainer,
    TableHead,
    TableHeader,
    TableRow,
} from "@carbon/react";
import { useQuery } from "@tanstack/react-query";
import type { SelfApplicationRoleDto } from "fam-api";
import type { FC } from "react";
import { PageTitle } from "@/components/PageTitle";
import { StepContainer } from "@/components/StepContainer";
import { TableSkeleton } from "@/components/TableSkeleton";
import { PLACE_HOLDER } from "@/constants/constants";
import { useErrorToast } from "@/context/notification/useErrorToast";
import {
    fetchSelfApplicationRoles,
    fetchSelfPermissions,
} from "@/services/AuthApiService";
import "./MyPermissions.css";

/**
 * What the signed-in user holds, in two parts.
 *
 * They come from different places and at different speeds, which is why they are
 * two queries rather than one:
 *
 * - what they may <b>administer</b> is on their token, so it is immediate;
 * - what they hold <b>as a user</b> of each application lives in CSS, one
 *   request per integration and environment, so it is slow enough to notice.
 *
 * Fetching them together would make the fast half wait for the slow one.
 */

/**
 * Every scope the role is held under, joined - "DCC", or "DCC, 00001018" for a
 * role scoped by both.
 */
const scopeOf = (role: SelfApplicationRoleDto): string =>
    (role.scopes ?? [])
        .map((scope) => scope.label || scope.value)
        .join(", ");

/** Shared with the loading skeletons so headers and columns cannot drift. */
const ROLE_HEADERS = [
    "Application",
    "Environment",
    "Role",
    "Description",
    "District / client",
];

const PERMISSION_HEADERS = ["Application", "Environment", "Role"];

export const MyPermissions: FC = () => {
    const permissionsQuery = useQuery({
        queryKey: ["self-permissions"],
        queryFn: fetchSelfPermissions,
        // Roles change through this very application, so a stale list is
        // confusing.
        refetchOnMount: true,
    });

    const applicationRolesQuery = useQuery({
        queryKey: ["self-application-roles"],
        queryFn: fetchSelfApplicationRoles,
        refetchOnMount: true,
    });

    const applicationRoles = applicationRolesQuery.data ?? [];
    const permissions = permissionsQuery.data ?? [];

    useErrorToast({
        when: applicationRolesQuery.isError,
        title: "Your application roles could not be loaded",
        subtitle: "Please try again.",
        occurrence: applicationRolesQuery.errorUpdatedAt,
    });

    useErrorToast({
        when: permissionsQuery.isError,
        title: "Your permissions could not be loaded",
        subtitle: "Please try again.",
        occurrence: permissionsQuery.errorUpdatedAt,
    });

    return (
        <div className="my-permissions-container">
            <PageTitle
                title="My permissions"
                subtitle="The applications you can use, and what you can administer"
            />

            <StepContainer title="Application roles" divider>
                <p className="section-note">
                    The roles you hold as a user of each application.
                </p>

                <div className="fam-table">
                    {applicationRolesQuery.isLoading ? (
                        <TableSkeleton headers={ROLE_HEADERS} />
                    ) : (
                    <TableContainer>
                        <Table size="md" useZebraStyles>
                            <TableHead>
                                <TableRow>
                                    {ROLE_HEADERS.map((header) => (
                                        <TableHeader key={header}>
                                            {header}
                                        </TableHeader>
                                    ))}
                                </TableRow>
                            </TableHead>
                            <TableBody>
                                {applicationRoles.length === 0 ? (
                                    <TableRow>
                                        <TableCell colSpan={ROLE_HEADERS.length}>
                                            {/*
                                                Telling somebody they hold no
                                                roles when the list never
                                                arrived is worse than telling
                                                them nothing.
                                            */}
                                            {applicationRolesQuery.isError
                                                ? "Your application roles could not be loaded."
                                                : "You hold no roles in any application"}
                                        </TableCell>
                                    </TableRow>
                                ) : (
                                    /*
                                        A scoped role is one CSS role per district
                                        or client, so somebody granted three
                                        districts holds three roles and gets three
                                        rows - which is what they actually have.
                                    */
                                    applicationRoles.map((role, index) => (
                                        <TableRow
                                            key={`${role.application_name}-${role.environment}-${role.base_role_name}-${scopeOf(role)}-${index}`}
                                        >
                                            <TableCell>
                                                {role.application_name}
                                            </TableCell>
                                            <TableCell>
                                                {role.environment.toUpperCase()}
                                            </TableCell>
                                            <TableCell>
                                                {role.role_display_name ??
                                                    role.base_role_name}
                                            </TableCell>
                                            <TableCell>
                                                {role.role_description ?? (
                                                    <span className="not-applicable">
                                                        {PLACE_HOLDER}
                                                    </span>
                                                )}
                                            </TableCell>
                                            <TableCell>
                                                {scopeOf(role) || (
                                                    <span className="not-applicable">
                                                        {PLACE_HOLDER}
                                                    </span>
                                                )}
                                            </TableCell>
                                        </TableRow>
                                    ))
                                )}
                            </TableBody>
                        </Table>
                    </TableContainer>
                    )}
                </div>
            </StepContainer>

            <StepContainer title="Administrative permissions">
                <p className="section-note">What you can administer in FAM.</p>

                <div className="fam-table">
                    {permissionsQuery.isLoading ? (
                        <TableSkeleton headers={PERMISSION_HEADERS} />
                    ) : (
                    <TableContainer>
                        <Table size="md" useZebraStyles>
                            <TableHead>
                                <TableRow>
                                    {PERMISSION_HEADERS.map((header) => (
                                        <TableHeader key={header}>
                                            {header}
                                        </TableHeader>
                                    ))}
                                </TableRow>
                            </TableHead>
                            <TableBody>
                                {permissions.length === 0 ? (
                                    <TableRow>
                                        <TableCell
                                            colSpan={PERMISSION_HEADERS.length}
                                        >
                                            {permissionsQuery.isError
                                                ? "Your permissions could not be loaded."
                                                : "You do not administer any applications"}
                                        </TableCell>
                                    </TableRow>
                                ) : (
                                    permissions.map((permission, index) => (
                                        <TableRow
                                            key={`${permission.role}-${permission.css_integration_id ?? "all"}-${permission.environment ?? "all"}-${index}`}
                                        >
                                            <TableCell>
                                                {permission.application_name}
                                            </TableCell>
                                            {/*
                                                FAM_ADMIN names no application
                                                and no environment, because it
                                                administers every one.
                                            */}
                                            <TableCell>
                                                {permission.environment ? (
                                                    permission.environment.toUpperCase()
                                                ) : (
                                                    <span className="not-applicable">
                                                        {PLACE_HOLDER}
                                                    </span>
                                                )}
                                            </TableCell>
                                            <TableCell>
                                                {permission.role_description}
                                            </TableCell>
                                        </TableRow>
                                    ))
                                )}
                            </TableBody>
                        </Table>
                    </TableContainer>
                    )}
                </div>
            </StepContainer>
        </div>
    );
};

export default MyPermissions;

// frontend/src/views/MyPermissions/index.vue
<script setup lang="ts">
import ErrorText from "@/components/UI/ErrorText.vue";
import { TABLE_DATATABLE_PT } from "@/passthrough/datatable/datatablePassThrough";
import PageTitle from "@/components/UI/PageTitle.vue";
import StepContainer from "@/components/UI/StepContainer.vue";
import {
    fetchSelfApplicationRoles,
    fetchSelfPermissions,
} from "@/services/AuthApiService";
import { useQuery } from "@tanstack/vue-query";
import type { SelfApplicationRoleDto, SelfPermissionDto } from "fam-api";
import Column from "primevue/column";
import DataTable from "primevue/datatable";
import { computed } from "vue";

/**
 * What the signed-in user holds, in two parts.
 *
 * They come from different places and at different speeds, which is why they are
 * two queries rather than one:
 *
 * - what they may **administer** is on their token, so it is immediate;
 * - what they hold **as a user** of each application lives in CSS, one request
 *   per integration and environment, so it is slow enough to notice.
 *
 * Fetching them together would make the fast half wait for the slow one.
 */
const permissionsQuery = useQuery({
    queryKey: ["self-permissions"],
    queryFn: fetchSelfPermissions,
    // Roles change through this very application, so a stale list is confusing.
    refetchOnMount: true,
});

const applicationRolesQuery = useQuery({
    queryKey: ["self-application-roles"],
    queryFn: fetchSelfApplicationRoles,
    refetchOnMount: true,
});

const permissions = computed<SelfPermissionDto[]>(
    () => permissionsQuery.data.value ?? []
);

const applicationRoles = computed<SelfApplicationRoleDto[]>(
    () => applicationRolesQuery.data.value ?? []
);

/**
 * Every scope the role is held under, joined - "DCC", or "DCC, 00001018" for a
 * role scoped by both. An em dash when it is not scoped.
 */
const scopeOf = (role: SelfApplicationRoleDto): string =>
    role.scopes?.length
        ? role.scopes.map((scope) => scope.label || scope.value).join(", ")
        : "—";
</script>

<template>
    <div class="my-permissions-container">
        <PageTitle
            title="My permissions"
            subtitle="The applications you can use, and what you can administer"
        />

        <StepContainer title="Application roles" divider class="application-roles">
            <p class="section-note">
                The roles you hold as a user of each application. Only
                applications FAM administers are listed - a role in an
                application managed by another team is not visible here.
            </p>

            <ErrorText
                v-if="applicationRolesQuery.isError.value"
                show-icon
                error-msg="Your application roles could not be loaded. Please try again."
            />

            <DataTable
                :pt="TABLE_DATATABLE_PT"
                class="fam-table"
                :value="applicationRoles"
            >
                <template #empty>
                    {{
                        applicationRolesQuery.isLoading.value
                            ? "Checking every application…"
                            : "You hold no roles in any application"
                    }}
                </template>

                <Column header="Application" field="application_name" />

                <Column header="Environment">
                    <template #body="{ data }">
                        {{ data.environment.toUpperCase() }}
                    </template>
                </Column>

                <Column header="Role">
                    <template #body="{ data }">
                        {{ data.role_display_name ?? data.base_role_name }}
                    </template>
                </Column>

                <Column header="Description">
                    <template #body="{ data }">
                        <span v-if="data.role_description">
                            {{ data.role_description }}
                        </span>
                        <span v-else class="not-applicable">—</span>
                    </template>
                </Column>

                <!--
                    A scoped role is one CSS role per district or client, so
                    somebody granted three districts holds three roles and gets
                    three rows - which is what they actually have.
                -->
                <Column header="District / client">
                    <template #body="{ data }">
                        <span v-if="data.scopes?.length">{{ scopeOf(data) }}</span>
                        <span v-else class="not-applicable">—</span>
                    </template>
                </Column>
            </DataTable>
        </StepContainer>

        <StepContainer title="Administrative permissions">
            <p class="section-note">
                What you can administer in FAM.
            </p>

            <ErrorText
                v-if="permissionsQuery.isError.value"
                show-icon
                error-msg="Your permissions could not be loaded. Please try again."
            />

            <DataTable class="fam-table" :value="permissions">
                <template #empty>
                    {{
                        permissionsQuery.isLoading.value
                            ? "Loading your permissions…"
                            : "You do not administer any applications"
                    }}
                </template>

                <Column header="Application" field="application_name" />

                <Column header="Environment">
                    <template #body="{ data }">
                        <!--
                            FAM_ADMIN names no application and no environment,
                            because it administers every one.
                        -->
                        <span v-if="data.environment">
                            {{ data.environment.toUpperCase() }}
                        </span>
                        <span v-else class="not-applicable">—</span>
                    </template>
                </Column>

                <Column header="Role" field="role_description" />
            </DataTable>
        </StepContainer>
    </div>
</template>

<style lang="scss">
@use "@/passthrough/datatable/datatablePassThrough.scss";
.my-permissions-container {
    padding-bottom: 2.5rem;

    /*
        Separates the first section from the page title, 34px to 58px.

        padding, not margin: the heading's own 20px top margin sits inside the
        step container with nothing between, so a margin-top here would collapse
        with it and add almost nothing.
    */
    .application-roles {
        padding-top: 1.5rem;
    }

    .section-note {
        margin-bottom: 1.5rem;
        max-width: 46rem;
        color: var(--semantic-color-text-secondary);
    }

    .not-applicable {
        color: var(--semantic-color-text-secondary);
    }
}
</style>
