// frontend/src/providers/AuthProvider.vue
<script setup lang="ts">
import { ref, provide, onMounted, onBeforeUnmount, readonly } from "vue";
import axios from "axios";
import type { User } from "oidc-client-ts";
import type { IdpTypes, AuthContext, FamLoginUser } from "@/types/AuthTypes";
import { AUTH_KEY } from "@/constants/InjectionKeys";
import { ONE_SECOND, THREE_MINUTES, HALF_HOUR } from "@/constants/TimeUnits";
import { IdpProvider } from "@/enum/IdpEnum";
import { EnvironmentSettings } from "@/services/EnvironmentSettings";
import {
    getUserManager,
    loadStoredUser,
    KC_IDP_HINT,
    AUTH_CALLBACK_PATH,
} from "@/services/keycloak";
import { bootstrapLogin, fetchSelf } from "@/services/AuthApiService";
import { authState } from "@/providers/authState";
import { useRouter } from "vue-router";
import Spinner from "@/components/UI/Spinner.vue";

const environmentSettings = new EnvironmentSettings();
const REFRESH_INTERVAL = THREE_MINUTES;
const INACTIVITY_TIMEOUT = HALF_HOUR;

let refreshIntervalId: number | null = null;
let inactivityTimeoutId: number | null = null;
const isLoading = ref(false); // Loading state for animation
const router = useRouter();

const setAxiosAuthorizationHeader = (token: string) => {
    axios.defaults.headers.common["Authorization"] = `Bearer ${token}`;
};

/**
 * Resets the inactivity timeout and sets a new timeout to log the user out after a period of inactivity.
 * If the user is inactive (no mouse or keyboard input) for the defined `INACTIVITY_TIMEOUT`,
 * and is still authenticated, they will be logged out and the silent refresh will stop.
 */
const resetInactivityTimeout = () => {
    if (inactivityTimeoutId) clearTimeout(inactivityTimeoutId);

    inactivityTimeoutId = window.setTimeout(() => {
        if (authState.value.isAuthenticated) {
            console.log("User inactive, logging out.");
            logout();
        }
    }, INACTIVITY_TIMEOUT);
};

/**
 * Stops the silent token refresh process.
 */
const stopSilentRefresh = () => {
    if (refreshIntervalId) clearInterval(refreshIntervalId);
    refreshIntervalId = null;
};

/**
 * Starts a sign-in redirect to BC Gov SSO.
 *
 * `kc_idp_hint` sends the browser straight to the chosen provider rather than
 * Keycloak's provider-selection screen, preserving the two-button landing page.
 *
 * @param {IdpTypes} idP The identity provider (IDIR or Business BCeID).
 */
const login = async (idP: IdpTypes) => {
    try {
        await getUserManager().signinRedirect({
            extraQueryParams: {
                kc_idp_hint:
                    idP === IdpProvider.IDIR
                        ? KC_IDP_HINT.IDIR
                        : KC_IDP_HINT.BCEIDBUSINESS,
            },
        });
    } catch (error) {
        console.error("Login failed:", error);
    }
};

/**
 * Logs the user out and resets authentication state.
 *
 * Redirects through Keycloak's end-session endpoint, which ends the realm
 * session and returns to `post_logout_redirect_uri` - the app origin, set in
 * `keycloak.ts`. That origin must be on the client's post-logout redirect
 * allow-list in the realm, or Keycloak refuses the return leg.
 *
 * This ends the Keycloak session only. An upstream Siteminder session, if the
 * provider has one, outlives it - so a later sign-in through that provider may
 * not prompt for credentials again.
 *
 * Local state is cleared first, but the stored user is left for
 * `signoutRedirect` to remove: it needs the id_token_hint to tell Keycloak which
 * session to end.
 */
const logout = async () => {
    stopSilentRefresh();

    delete axios.defaults.headers.common["Authorization"];

    authState.value = {
        isAuthenticated: false,
        famLoginUser: null,
        isAuthRestored: true,
        accessRoles: [],
    };

    await getUserManager().signoutRedirect();
};

/**
 * Extracts display information from the token's profile claims.
 *
 * Claim names come from BC Gov SSO's identity mappers, replacing Cognito's
 * `custom:idp_*` attributes:
 *   - IDIR:           `idir_username`
 *   - Business BCeID: `bceid_username`, `bceid_business_name`
 */
const getFamLoginUser = (user: User): FamLoginUser => {
    const profile = user.profile as Record<string, any>;
    const identityProvider = (profile["identity_provider"] as string)?.toLowerCase();

    return {
        username:
            profile["idir_username"] ?? profile["bceid_username"] ?? undefined,
        displayName: profile["display_name"] ?? profile["name"],
        email: profile["email"],
        idpProvider: identityProvider,
        organization: profile["bceid_business_name"],
    };
};

/**
 * Completes the sign-in redirect, provisions the FAM user and starts the session.
 */
const handlePostLogin = async () => {
    try {
        isLoading.value = true;

        // Exchanges the authorization code and stores the resulting user.
        const user = await getUserManager().signinRedirectCallback();
        applySession(user);

        // Replaces the Cognito pre-token trigger: creates the fam_user row and
        // resolves roles. Must happen before any other API call.
        applyAccessRoles((await bootstrapLogin()).access_roles ?? []);

        // After the roles, as in loadUser: this is what releases the route
        // guards, and they decide admin-only routes from accessRoles.
        authState.value = { ...authState.value, isAuthRestored: true };

        startSilentRefresh();
        resetInactivityTimeout();

        /*
         * Remove the 'authCallback' part from the browser URL without disrupting
         * Vue Router's state, so the fragment does not linger and the auth guard
         * has one fewer comparison to make.
         */
        const newUrl = window.location.href.replace(
            new RegExp(`${AUTH_CALLBACK_PATH.replace("/", "")}.*`),
            ""
        );
        history.replaceState(null, "", newUrl);

        router.push("/manage-permissions");
    } catch (error) {
        console.log("Authentication Error:", error);
        logout();
    } finally {
        isLoading.value = false;
    }
};

/**
 * Restores the user's session on page reload if the user is already signed in.
 */
const restoreSession = async () => {
    try {
        isLoading.value = true;
        await loadUser();
        startSilentRefresh();
        resetInactivityTimeout();
    } catch (error) {
        console.warn(error);
        authState.value = {
            isAuthenticated: false,
            famLoginUser: null,
            isAuthRestored: true,
            accessRoles: [],
        };
    } finally {
        isLoading.value = false;
    }
};

/**
 * Publishes an authenticated session: sets the axios bearer header and the
 * shared auth state.
 */
const applySession = (user: User) => {
    authState.value = {
        isAuthenticated: true,
        famLoginUser: getFamLoginUser(user),
        // NOT set here. The route guards wait on this flag and then read the
        // roles, so publishing it before /auth/self has answered told them the
        // session was ready while accessRoles was still empty - on a refresh
        // that sent a FAM administrator straight to /no-access. loadUser sets it
        // once the roles are known.
        isAuthRestored: authState.value.isAuthRestored,
        // Carried across rather than cleared: this runs on every silent refresh,
        // and blanking the roles until /auth/self answers again would make
        // admin-only navigation flicker out every few minutes.
        accessRoles: authState.value.accessRoles,
    };
    setAxiosAuthorizationHeader(user.access_token);
};

/**
 * Publishes the roles the backend resolved for this caller.
 *
 * They decide what the UI offers. They are not what makes an action allowed -
 * every endpoint re-checks on its own, so a tampered value changes what the
 * screen shows and nothing else.
 */
const applyAccessRoles = (accessRoles: string[]) => {
    authState.value = { ...authState.value, accessRoles };
};

/**
 * Publishes the restored session, or throws when nobody is signed in.
 *
 * The "should this renew at all" rule lives in {@link loadStoredUser} - see
 * there for why an absent user must not trigger a silent renewal.
 */
const loadUser = async (): Promise<void> => {
    const user = await loadStoredUser(getUserManager());

    if (!user || !user.access_token) {
        throw new Error("The user is not authenticated");
    }

    applySession(user);

    // Re-read identity and roles so a permission change is picked up without a
    // fresh sign-in. Roles live in the database now, not in the token.
    applyAccessRoles((await fetchSelf()).access_roles ?? []);

    // Last, and only now: the guards treat this as "the session is ready to be
    // judged", and judging it needs the roles. Setting it in applySession left a
    // window where isAuthenticated was true and accessRoles was still empty.
    authState.value = { ...authState.value, isAuthRestored: true };
};

/**
 * Prevents concurrent token refresh attempts, reducing potential race conditions.
 */
let isRefreshing = false;

/**
 * Starts silent token refresh process for the authenticated user.
 */
const startSilentRefresh = () => {
    if (refreshIntervalId) clearInterval(refreshIntervalId);

    refreshIntervalId = setInterval(async () => {
        if (isRefreshing) return;
        try {
            isRefreshing = true;
            await loadUser();
        } catch (error) {
            console.error("Silent refresh failed:", error);
            logout();
        } finally {
            isRefreshing = false;
        }
    }, REFRESH_INTERVAL) as unknown as number;
};

/**
 * Creates a debounced version of the provided function, ensuring it is not
 * called more frequently than the specified delay.
 *
 * Used so `resetInactivityTimeout` is not triggered on every mouse move.
 */
const debounce = <T extends (...args: any[]) => void>(
    func: T,
    delay: number
): T => {
    let timer: ReturnType<typeof setTimeout> | null = null;

    return ((...args: Parameters<T>) => {
        if (timer) clearTimeout(timer);
        timer = setTimeout(() => func(...args), delay);
    }) as T;
};

const debouncedResetInactivityTimeout = debounce(
    resetInactivityTimeout,
    ONE_SECOND
);

/**
 * Lifecycle hook that runs when the component is mounted.
 * - Adds event listeners for user activity to reset the inactivity timeout.
 * - On the `/authCallback` path, completes the sign-in.
 * - Otherwise, attempts to restore an existing session.
 */
onMounted(() => {
    window.addEventListener("mousemove", debouncedResetInactivityTimeout);
    window.addEventListener("keydown", debouncedResetInactivityTimeout);
    window.addEventListener("click", debouncedResetInactivityTimeout);

    const currentPath = window.location.pathname;
    if (currentPath === AUTH_CALLBACK_PATH) {
        handlePostLogin();
    } else {
        restoreSession();
    }
});

/**
 * Lifecycle hook that runs when the component is about to be unmounted.
 */
onBeforeUnmount(() => {
    stopSilentRefresh();

    if (inactivityTimeoutId) {
        clearTimeout(inactivityTimeoutId);
    }

    window.removeEventListener("mousemove", debouncedResetInactivityTimeout);
    window.removeEventListener("keydown", debouncedResetInactivityTimeout);
    window.removeEventListener("click", debouncedResetInactivityTimeout);
});

/**
 * Provides authentication state and functions for use in components.
 */
provide<AuthContext>(AUTH_KEY, {
    get authState() {
        return readonly(authState.value);
    },
    login,
    logout,
    handlePostLogin,
});
</script>

<template>
    <div v-if="isLoading" class="auth-callback-container">
        <Spinner loading-text="Page loading" />
    </div>
    <slot v-else />
</template>

<style lang="scss" scoped>
.auth-callback-container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    width: 100vw;
}
</style>

// frontend/src/context/auth/AuthProvider.tsx
import { Loading } from "@carbon/react";
import axios from "axios";
import type { User } from "oidc-client-ts";
import { useCallback, useEffect, useRef, useState, type ReactNode } from "react";
import { useNavigate } from "react-router-dom";
import { bootstrapLogin, fetchSelf } from "@/services/AuthApiService";
import {
    AUTH_CALLBACK_PATH,
    getUserManager,
    KC_IDP_HINT,
    loadStoredUser,
} from "@/services/keycloak";
import { ROUTES } from "@/routes/routePaths";
import type { AuthState, FamLoginUser, IdpTypes } from "@/types/AuthTypes";
import { IdpProvider } from "@/enum/IdpEnum";
import { AuthContext } from "./AuthContext";

const ONE_SECOND = 1000;
const THREE_MINUTES = 3 * 60 * ONE_SECOND;
const HALF_HOUR = 30 * 60 * ONE_SECOND;

const REFRESH_INTERVAL = THREE_MINUTES;
const INACTIVITY_TIMEOUT = HALF_HOUR;

const SIGNED_OUT: AuthState = {
    isAuthenticated: false,
    famLoginUser: null,
    isAuthRestored: false,
    accessRoles: [],
};

/**
 * Display information from the token's profile claims.
 *
 * Claim names come from BC Gov SSO's identity mappers:
 *   - IDIR:           `idir_username`
 *   - Business BCeID: `bceid_username`, `bceid_business_name`
 */
const getFamLoginUser = (user: User): FamLoginUser => {
    const profile = user.profile as Record<string, unknown>;
    return {
        username:
            (profile["idir_username"] as string) ??
            (profile["bceid_username"] as string) ??
            undefined,
        displayName:
            (profile["display_name"] as string) ?? (profile["name"] as string),
        email: profile["email"] as string,
        idpProvider: (profile["identity_provider"] as string)?.toLowerCase(),
        organization: profile["bceid_business_name"] as string,
    };
};

export const AuthProvider = ({ children }: { children: ReactNode }) => {
    const [authState, setAuthState] = useState<AuthState>(SIGNED_OUT);
    const [isLoading, setLoading] = useState(true);
    const navigate = useNavigate();

    // Timers and re-entrancy flags live in refs: changing them must not
    // re-render, and a re-render must not restart them.
    const refreshIntervalId = useRef<number | null>(null);
    const inactivityTimeoutId = useRef<number | null>(null);
    const isRefreshing = useRef(false);
    const bootstrapped = useRef(false);

    const stopSilentRefresh = useCallback(() => {
        if (refreshIntervalId.current) {
            clearInterval(refreshIntervalId.current);
        }
        refreshIntervalId.current = null;
    }, []);

    /**
     * Ends the Keycloak session.
     *
     * <b>The stored user is deliberately left in place.</b> oidc-client-ts reads
     * `id_token_hint` off it and removes it itself; clearing it here first sends
     * a logout Keycloak cannot attribute to a session, so the realm session
     * survives and the next sign-in walks straight back in.
     */
    const logout = useCallback(async () => {
        stopSilentRefresh();
        delete axios.defaults.headers.common["Authorization"];
        setAuthState({ ...SIGNED_OUT, isAuthRestored: true });
        await getUserManager().signoutRedirect();
    }, [stopSilentRefresh]);

    const resetInactivityTimeout = useCallback(() => {
        if (inactivityTimeoutId.current) {
            clearTimeout(inactivityTimeoutId.current);
        }
        inactivityTimeoutId.current = window.setTimeout(() => {
            // Read from the setter rather than a captured value: this closure
            // outlives the render that made it, and a stale `isAuthenticated`
            // would either log out a signed-out user or never log out at all.
            setAuthState((current) => {
                if (current.isAuthenticated) {
                    void logout();
                }
                return current;
            });
        }, INACTIVITY_TIMEOUT);
    }, [logout]);

    /** Publishes the session. Not `isAuthRestored` - see loadUser. */
    const applySession = useCallback((user: User) => {
        axios.defaults.headers.common["Authorization"] =
            `Bearer ${user.access_token}`;
        setAuthState((current) => ({
            ...current,
            isAuthenticated: true,
            famLoginUser: getFamLoginUser(user),
        }));
    }, []);

    /**
     * Restores a stored session, or throws when nobody is signed in.
     *
     * Roles are re-read on every refresh so a permission change takes effect
     * without a fresh sign-in - they live in CSS, not in the token.
     */
    const loadUser = useCallback(async () => {
        const user = await loadStoredUser(getUserManager());
        if (!user?.access_token) {
            throw new Error("The user is not authenticated");
        }
        applySession(user);

        const accessRoles = (await fetchSelf()).access_roles ?? [];

        // Last, and only now. The route guards treat this as "the session is
        // ready to be judged", and judging it needs the roles: setting it in
        // applySession left a window where a FAM administrator was judged with
        // an empty role list and sent to /no-access.
        setAuthState((current) => ({
            ...current,
            accessRoles,
            isAuthRestored: true,
        }));
    }, [applySession]);

    const startSilentRefresh = useCallback(() => {
        stopSilentRefresh();
        refreshIntervalId.current = window.setInterval(async () => {
            if (isRefreshing.current) {
                return;
            }
            try {
                isRefreshing.current = true;
                await loadUser();
            } catch (error) {
                console.error("Silent refresh failed:", error);
                void logout();
            } finally {
                isRefreshing.current = false;
            }
        }, REFRESH_INTERVAL);
    }, [loadUser, logout, stopSilentRefresh]);

    const login = useCallback(async (idp: IdpTypes) => {
        try {
            await getUserManager().signinRedirect({
                extraQueryParams: {
                    kc_idp_hint:
                        idp === IdpProvider.IDIR
                            ? KC_IDP_HINT.IDIR
                            : KC_IDP_HINT.BCEIDBUSINESS,
                },
            });
        } catch (error) {
            console.error("Login failed:", error);
        }
    }, []);

    useEffect(() => {
        // React 19 StrictMode mounts effects twice in development. The
        // authorization code is single-use, so a second exchange fails and
        // would log the user straight back out - this runs once either way.
        if (bootstrapped.current) {
            return;
        }
        bootstrapped.current = true;

        const onActivity = debounce(resetInactivityTimeout, ONE_SECOND);
        window.addEventListener("mousemove", onActivity);
        window.addEventListener("keydown", onActivity);
        window.addEventListener("click", onActivity);

        const start = async () => {
            try {
                if (window.location.pathname === AUTH_CALLBACK_PATH) {
                    const user =
                        await getUserManager().signinRedirectCallback();
                    applySession(user);
                    const accessRoles =
                        (await bootstrapLogin()).access_roles ?? [];
                    setAuthState((current) => ({
                        ...current,
                        accessRoles,
                        isAuthRestored: true,
                    }));
                    startSilentRefresh();
                    resetInactivityTimeout();
                    navigate(ROUTES.managePermissions, { replace: true });
                    return;
                }

                await loadUser();
                startSilentRefresh();
                resetInactivityTimeout();
            } catch (error) {
                // Distinguishes "nobody is signed in" from "the session was
                // refused". The Vue version logged both as one warning and
                // de-authenticated, so a backend rejecting every token looked
                // identical to a first visit - which cost an afternoon.
                const status = (error as { response?: { status?: number } })
                    ?.response?.status;
                if (status === 401 || status === 403) {
                    console.error(
                        `The API refused this session (HTTP ${status}). The token is ` +
                            "being rejected - check that the SPA and the backend " +
                            "agree on the realm and client.",
                        error
                    );
                } else {
                    console.info("No session to restore.", error);
                }
                setAuthState({ ...SIGNED_OUT, isAuthRestored: true });
            } finally {
                setLoading(false);
            }
        };

        void start();

        return () => {
            stopSilentRefresh();
            if (inactivityTimeoutId.current) {
                clearTimeout(inactivityTimeoutId.current);
            }
            window.removeEventListener("mousemove", onActivity);
            window.removeEventListener("keydown", onActivity);
            window.removeEventListener("click", onActivity);
        };
        // Intentionally once: the guard above makes re-runs no-ops, and the
        // callbacks are stable.
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    if (isLoading) {
        return <Loading description="Signing in" withOverlay />;
    }

    return (
        <AuthContext.Provider value={{ authState, login, logout }}>
            {children}
        </AuthContext.Provider>
    );
};

/** So a mouse move does not reset the inactivity timer on every pixel. */
function debounce<T extends (...args: never[]) => void>(fn: T, delay: number) {
    let timer: ReturnType<typeof setTimeout> | null = null;
    return (...args: Parameters<T>) => {
        if (timer) {
            clearTimeout(timer);
        }
        timer = setTimeout(() => fn(...args), delay);
    };
}
