// frontend/src/views/UserPermissionHistory/index.vue
<script setup lang="ts">
import UserPermissionHistoryTable from "@/components/UserPermissionHistoryTable/index.vue";
import BreadCrumbs from "@/components/UI/BreadCrumbs.vue";
import Button from "@/components/UI/Button.vue";
import PageTitle from "@/components/UI/PageTitle.vue";
import { ManagePermissionsRoute } from "@/router/routes";
import type { BreadCrumbType } from "@/types/BreadCrumbTypes";
import type { UserType } from "fam-api";
import { useRouter } from "vue-router";

/**
 * One user's permission history for one application.
 *
 * Reached from the permissions table. Keyed on the user's GUID rather than their
 * name: the audit trail keeps no foreign key into any user record, so that it
 * survives the user being renamed or removed.
 */
const props = defineProps<{
    targetUserGuid: string;
    targetUserType: UserType;
    integrationId: number;
    environment: string;
    userName: string;
}>();

const router = useRouter();

const crumbs: BreadCrumbType[] = [
    { routeName: ManagePermissionsRoute.name as string, label: "Manage permissions" },
];

const navigateBack = () => router.push({ name: ManagePermissionsRoute.name });
</script>

<template>
    <div class="user-detail-page-container">
        <BreadCrumbs :crumbs="crumbs" />

        <PageTitle
            class="user-detail-page-title"
            title="Permissions History"
            :subtitle="`Check ${props.userName}'s permission history`"
        />

        <div class="gray-container">
            <UserPermissionHistoryTable
                :target-user-guid="props.targetUserGuid"
                :target-user-type="props.targetUserType"
                :integration-id="props.integrationId"
                :environment="props.environment"
            />

            <div class="back-button-container">
                <Button
                    label="Back"
                    severity="secondary"
                    @click="navigateBack"
                />
            </div>
        </div>
    </div>
</template>

<style lang="scss">
.user-detail-page-container {
    .user-detail-page-title {
        margin-bottom: 1.5rem;
    }

    .gray-container {
        display: flex;
        flex-direction: column;
        margin: 2.5rem -2.5rem 0 -2.5rem;
        background: var(--semantic-color-surface-layer-1);
        min-height: calc(100vh - 19rem);
        padding: 2.5rem;
    }

    .back-button-container {
        margin-top: 2rem;
    }
}
</style>

// frontend/src/pages/UserPermissionHistory/index.tsx
import { Breadcrumb, BreadcrumbItem, Button } from "@carbon/react";
import type { UserType } from "fam-api";
import type { FC } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { PageTitle } from "@/components/PageTitle";
import { UserPermissionHistoryTable } from "@/components/UserPermissionHistoryTable";
import { ROUTES } from "@/routes/routePaths";
import "./UserPermissionHistory.css";

/**
 * One user's permission history for one application.
 *
 * Reached from the permissions table. Keyed on the user's GUID rather than their
 * name: the audit trail keeps no foreign key into any user record, so that it
 * survives the user being renamed or removed.
 */
export const UserPermissionHistory: FC = () => {
    const navigate = useNavigate();
    const [params] = useSearchParams();

    const targetUserGuid = params.get("targetUserGuid") ?? "";
    const targetUserType = (params.get("targetUserType") ?? "IDIR") as UserType;
    const integrationId = Number(params.get("integrationId"));
    const environment = params.get("environment") ?? "";
    const userName = params.get("userName") ?? "";

    return (
        <div className="user-detail-page-container">
            <Breadcrumb noTrailingSlash>
                <BreadcrumbItem>
                    <Link to={ROUTES.managePermissions}>Manage permissions</Link>
                </BreadcrumbItem>
            </Breadcrumb>

            <PageTitle
                title="Permissions History"
                subtitle={`Check ${userName}'s permission history`}
            />

            <div className="gray-container">
                <UserPermissionHistoryTable
                    targetUserGuid={targetUserGuid}
                    targetUserType={targetUserType}
                    integrationId={integrationId}
                    environment={environment}
                />

                <div className="back-button-container">
                    <Button
                        kind="secondary"
                        onClick={() => navigate(ROUTES.managePermissions)}
                    >
                        Back
                    </Button>
                </div>
            </div>
        </div>
    );
};

export default UserPermissionHistory;
