// frontend/src/components/Search/UserSearch.tsx
import { Search as SearchIcon } from "@carbon/icons-react";
import { Button, Select, SelectItem, TextInput } from "@carbon/react";
import { UserType } from "fam-api/model";
import {
    useEffect,
    useMemo,
    useRef,
    useState,
    type FC,
    type ReactNode,
} from "react";
import { InlineSpinner } from "@/components/InlineSpinner";
import { PERMISSION_REQUIRED_FOR_OPERATION } from "@/constants/ApiErrorCodes";
import { useAuth } from "@/context/auth/useAuth";
import { useUserSearch } from "@/hooks/useUserSearch";
import type { SelectedUser } from "@/types/SelectUserType";
import type { UserSearchType } from "@/types/UserSearchTypes";
import { UserSearchResultsModal } from "./UserSearchResultsModal";
import { UserSearchSelectedTable } from "./UserSearchSelectedTable";
import "./UserSearch.css";

/**
 * Find people in IDIR or BCeID and choose them for whatever the form does next.
 *
 * Owns the search fields, the results modal and the running selection; the form
 * around it is told the selection through `onSelectionChange` and never reaches
 * into it.
 */

const MAX_SEARCH_TEXT_LENGTH = 35; // The API allows 50; this is deliberately less.

const SELF_SELECTION_ERROR = "You cannot grant permissions to yourself.";

type DomainChangeRequest = {
    currentDomain: UserType;
    nextDomain: UserType;
    /** Already chosen, and about to be discarded if the change goes ahead. */
    selectedUsersCount: number;
    approveChange: () => void;
    cancelChange: () => void;
};

type Props = {
    environment: string;
    /** Several people at once, or exactly one. */
    multiUserMode: boolean;
    availableDomains?: UserType[];
    disabled?: boolean;
    searchButtonLabel?: string;
    helperText?: string;
    /**
     * Lets the signed-in user choose themselves.
     *
     * Off by default: granting yourself access is the thing an administrator
     * must not quietly do. On for the cases the backend permits, such as an
     * application admin self-granting on a dev or test application.
     */
    allowSelfSelection?: boolean;
    onSelectionChange: (users: SelectedUser[]) => void;
    onDomainChange?: (domain: UserType) => void;
    /**
     * A chance to stop a domain change before the selection is discarded.
     *
     * Without it the change is applied at once. With it, nothing happens until
     * the form calls approveChange - which is how the grant screens get to ask
     * "you have three people chosen, discard them?" first.
     */
    onBeforeDomainChange?: (request: DomainChangeRequest) => void;
    /** Errors from the form itself, shown alongside the search's own. */
    formError?: ReactNode;
};

const domainLabel = (domain: UserType) =>
    domain === UserType.Idir ? "IDIR" : "BCeID";

/** BCeID can only be looked up by exact username; IDIR admits a name search. */
const searchTypesFor = (
    domain: UserType
): Array<{ label: string; value: UserSearchType }> =>
    domain === UserType.BceidBus
        ? [{ label: "Username", value: "username" }]
        : [
              { label: "Username", value: "username" },
              { label: "First Name", value: "firstName" },
              { label: "Last Name", value: "lastName" },
          ];

export const UserSearch: FC<Props> = ({
    environment,
    multiUserMode,
    availableDomains = [UserType.Idir, UserType.BceidBus],
    disabled = false,
    searchButtonLabel = "Search",
    helperText = "",
    allowSelfSelection = false,
    onSelectionChange,
    onDomainChange,
    onBeforeDomainChange,
    formError,
}) => {
    const [domain, setDomain] = useState<UserType>(availableDomains[0]);
    const [searchType, setSearchType] = useState<UserSearchType>("username");
    const [searchText, setSearchText] = useState("");
    const [searchTextError, setSearchTextError] = useState("");
    const [resultMessage, setResultMessage] = useState("");
    const [selected, setSelected] = useState<SelectedUser[]>([]);
    const [isResultsOpen, setResultsOpen] = useState(false);

    const { authState } = useAuth();
    const { searchUsers, isPending, searchResults, isSuccess, searchError, reset } =
        useUserSearch();

    const currentUsername = (
        authState.famLoginUser?.username ?? ""
    ).toLowerCase();

    const searchTypes = useMemo(() => searchTypesFor(domain), [domain]);
    const isUsernameSearch = searchType === "username";

    /**
     * What is wrong with this text, or "" if nothing is.
     *
     * No spaces ever - no directory identifier contains one - and no digits on a
     * name search, where they only ever come from somebody typing a username
     * into the wrong field.
     */
    const invalidTextError = (value: string): string => {
        if (/\s/.test(value)) {
            return "Search text cannot contain spaces";
        }
        if (!isUsernameSearch && /\d/.test(value)) {
            return "Search text cannot contain numbers";
        }
        return "";
    };

    const validate = (): boolean => {
        const trimmed = searchText.trim();
        if (!trimmed) {
            setSearchTextError("Search text is required");
            return false;
        }
        if (trimmed.length > MAX_SEARCH_TEXT_LENGTH) {
            setSearchTextError(
                `Search text must be ${MAX_SEARCH_TEXT_LENGTH} characters or less`
            );
            return false;
        }
        const invalid = invalidTextError(trimmed);
        setSearchTextError(invalid);
        return !invalid;
    };

    const applyDomainChange = (next: UserType) => {
        setDomain(next);
        setSearchType(searchTypesFor(next)[0].value);
        setSearchText("");
        setSearchTextError("");
        setResultMessage("");
        // The people already chosen came from the other directory, so they go.
        setSelected([]);
        onSelectionChange([]);
        reset();
        onDomainChange?.(next);
    };

    const handleDomainSelection = (next: UserType) => {
        if (next === domain) {
            return;
        }
        if (!onBeforeDomainChange) {
            applyDomainChange(next);
            return;
        }
        onBeforeDomainChange({
            currentDomain: domain,
            nextDomain: next,
            selectedUsersCount: selected.length,
            approveChange: () => applyDomainChange(next),
            // Nothing to undo: the Select is driven by `domain`, which has not
            // moved. The Vue version had to force a re-render here to drag
            // PrimeVue's own internal value back.
            cancelChange: () => {},
        });
    };

    const handleTextChange = (value: string) => {
        // Refuses the character rather than accepting it and complaining: the
        // field cannot hold a space or (on a name search) a digit at all.
        const sanitized = isUsernameSearch
            ? value.replace(/\s/g, "")
            : value.replace(/[\s\d]/g, "");

        if (sanitized !== value) {
            setSearchTextError(invalidTextError(value));
        } else if (searchTextError) {
            setSearchTextError(invalidTextError(sanitized));
        }
        setSearchText(sanitized);
    };

    const handleSearch = () => {
        if (!validate()) {
            return;
        }
        // Caught before the request rather than filtered out of the results: the
        // person typed their own username, and telling them so is clearer than
        // an empty result set.
        if (
            !allowSelfSelection &&
            isUsernameSearch &&
            searchText.trim().toLowerCase() === currentUsername
        ) {
            setSearchTextError(SELF_SELECTION_ERROR);
            return;
        }
        setResultMessage("");
        searchUsers({
            domain,
            searchType,
            searchText: searchText.trim(),
            environment,
        });
    };

    /**
     * Opens the results once per search.
     *
     * The ref is what makes it once: `isSuccess` stays true afterwards, so
     * reacting to the flag alone reopened the modal on every later render -
     * including the one caused by closing it.
     */
    const handledResults = useRef<SelectedUser[] | null>(null);
    useEffect(() => {
        if (!isSuccess || !searchResults || handledResults.current === searchResults) {
            return;
        }
        handledResults.current = searchResults;
        if (searchResults.length === 0) {
            setResultMessage(
                "No search result found. Check the spelling or try another search."
            );
            return;
        }
        setResultMessage("");
        setResultsOpen(true);
    }, [isSuccess, searchResults]);

    useEffect(() => {
        if (!searchError) {
            return;
        }
        if (searchError.code === PERMISSION_REQUIRED_FOR_OPERATION) {
            // Naming the organisation is the point: a BCeID administrator gets
            // this when they reach outside their own, and the message is
            // otherwise indistinguishable from a general refusal.
            const orgName =
                authState.famLoginUser?.organization ?? "Unknown organization";
            setResultMessage(
                `${searchError.description ?? searchError.message}. Org name: ${orgName}`
            );
            return;
        }
        setResultMessage(searchError.message);
    }, [searchError, authState.famLoginUser?.organization]);

    const confirmSelection = (chosen: SelectedUser[]) => {
        setResultsOpen(false);
        if (chosen.length === 0) {
            return;
        }

        const admissible =
            currentUsername && !allowSelfSelection
                ? chosen.filter(
                      (user) => user.userId.toLowerCase() !== currentUsername
                  )
                : chosen;

        if (currentUsername && admissible.length !== chosen.length) {
            setResultMessage(SELF_SELECTION_ERROR);
        }

        const next = multiUserMode
            ? // Merged with what was already chosen, deduplicated on user and
              // directory together - the same id can exist in both.
              [...selected, ...admissible].filter(
                  (user, index, all) =>
                      index ===
                      all.findIndex(
                          (other) =>
                              other.userId.toLowerCase() ===
                                  user.userId.toLowerCase() &&
                              other.sourceDomain === user.sourceDomain
                      )
              )
            : admissible.slice(0, 1);

        setSelected(next);
        onSelectionChange(next);
    };

    const removeUser = (userId: string) => {
        const next = selected.filter(
            (user) => user.userId.toLowerCase() !== userId.toLowerCase()
        );
        setSelected(next);
        onSelectionChange(next);
    };

    return (
        <div className="user-search-container">
            <div className="search-fields-row">
                <Select
                    id="user-domain"
                    className="field-domain"
                    labelText="User domain"
                    value={domain}
                    onChange={(event) =>
                        handleDomainSelection(event.target.value as UserType)
                    }
                    disabled={disabled || availableDomains.length === 1 || isPending}
                >
                    {availableDomains.map((option) => (
                        <SelectItem
                            key={option}
                            value={option}
                            text={domainLabel(option)}
                        />
                    ))}
                </Select>

                <Select
                    id="search-type"
                    className="field-type"
                    labelText="Type"
                    value={searchType}
                    onChange={(event) => {
                        setSearchType(event.target.value as UserSearchType);
                        // The text may be legal for one type and not the other,
                        // so the complaint goes rather than being re-evaluated
                        // against a rule the user has not typed under yet.
                        setSearchTextError("");
                        setResultMessage("");
                    }}
                    disabled={disabled || isPending}
                >
                    {searchTypes.map((option) => (
                        <SelectItem
                            key={option.value}
                            value={option.value}
                            text={option.label}
                        />
                    ))}
                </Select>

                <div className="field-search-input">
                    <TextInput
                        id="user-search-input"
                        labelText="Search text"
                        hideLabel
                        placeholder="Please input search text"
                        maxLength={MAX_SEARCH_TEXT_LENGTH}
                        value={searchText}
                        onChange={(event) => handleTextChange(event.target.value)}
                        onKeyDown={(event) => {
                            if (event.key === "Enter") {
                                event.preventDefault();
                                handleSearch();
                            }
                        }}
                        invalid={Boolean(searchTextError)}
                        invalidText={searchTextError}
                        disabled={disabled || isPending}
                    />
                </div>

                <div className="field-search-button">
                    <Button
                        kind="tertiary"
                        // Carbon buttons default to `lg` (48px) while its inputs
                        // default to `md` (40px), so an unsized button stands a
                        // full 8px taller than the field beside it.
                        size="md"
                        name="searchUsers"
                        aria-label="Search users"
                        renderIcon={isPending ? InlineSpinner : SearchIcon}
                        disabled={disabled || isPending}
                        onClick={handleSearch}
                    >
                        {searchButtonLabel}
                    </Button>
                </div>
            </div>

            <div className="search-error-row">
                {helperText ? (
                    <p className="user-search__helper">{helperText}</p>
                ) : null}
                {resultMessage ? (
                    <p className="user-search__error" role="alert">
                        {resultMessage}
                    </p>
                ) : null}
                {formError}
            </div>

            <UserSearchSelectedTable
                users={selected}
                multiUserMode={multiUserMode}
                onDelete={removeUser}
            />

            <UserSearchResultsModal
                open={isResultsOpen}
                rows={searchResults ?? []}
                multiUserMode={multiUserMode}
                onConfirm={confirmSelection}
                onCancel={() => setResultsOpen(false)}
            />
        </div>
    );
};

export default UserSearch;

// frontend/src/components/Search/UserSearch.vue
<script setup lang="ts">
import UserSearchResultsDialog from "@/components/Search/UserSearchResultsDialog.vue";
import UserSearchSelectedTable from "@/components/Search/UserSearchSelectedTable.vue";
import Button from "@/components/UI/Button.vue";
import Dropdown from "@/components/UI/Dropdown.vue";
import HelperText from "@/components/UI/HelperText.vue";
import useAuth from "@/composables/useAuth";
import { useUserSearchApiService } from "@/composables/useUserSearchApiService";
import { PERMISSION_REQUIRED_FOR_OPERATION } from "@/constants/ApiErrorCodes";
import type { SelectedUser } from "@/types/SelectUserType";
import type { UserSearchType } from "@/types/UserSearchTypes";
import SearchIcon from "@carbon/icons-vue/es/search/16";
import { UserType } from "fam-api/model";
import type { SelectChangeEvent } from "primevue/select";
import InputText from "primevue/inputtext";
import { useDialog } from "primevue/usedialog";
import { computed, getCurrentInstance, ref, watch } from "vue";

/**
 * This component is intended to be a reusable user search component for searching users from IDIR/BCeID
 * and select them for further actions (e.g. granting permissions).
 * It provides an interface for searching users by different criteria (e.g. username, first name, last name)
 * and supports both single and multi user selection modes.
 * The component manages the state of search input, search results, and selected users, and communicates with
 *  parent component through emitted events to synchronize selected users and user domain changes.
 * It also handles input validation, error states, and provides user feedback through messages and a results dialog.
 */
const searchText = ref(""); // user input search value.
const searchTextError = ref(""); // error message for invalid search text
const searchResultMessage = ref(""); // message to display search result error or no results happens.
const latestConfirmedSelections = ref<SelectedUser[]>([]); // keep track of latest confirmed user selections.
const MAX_SEARCH_TEXT_LENGTH = 35; // limited to 35 although API allows up to 50.
const INVALID_SEARCH_TEXT_PATTERN_WITH_DIGITS = /[\s]/g; // no space (username allows digits)
const INVALID_SEARCH_TEXT_PATTERN = /[\s\d]/g; // no space, no numeric

const SELF_SELECTION_ERROR_MSG = "You cannot grant permissions to yourself.";

interface SelectOption<T> {
    label: string;
    value: T;
}

interface Props {
    environment: string;
    multiUserMode: boolean; // multi users (or single) selection
    availableDomains?: UserType[];
    disabled?: boolean;
    searchButtonLabel?: string;
    helperText?: string; // helper text to show below search input, can be used to provide guidance.
    allowSelfSelection?: boolean; // allow the logged on user to select/grant themselves (e.g. app admin self-granting on dev/test apps).
}

const props = withDefaults(defineProps<Props>(), {
    availableDomains: () => [UserType.Idir, UserType.BceidBus],
    disabled: false,
    searchButtonLabel: "Search",
    helperText: "",
    allowSelfSelection: false,
});

// Emits for parent component to react for changes in search.
const emit = defineEmits<{
    // Emitted before domain change takes effect. Giving parent component a chance to approve/cancel the change.
    "pre-user-domain-change": [
        payload: {
            currentDomain: UserType;
            nextDomain: UserType;
            selectedUsersCount: number; // existing users previously already selected and displayed at UserSearchSelectedTable.
            approveChange: () => void;
            cancelChange: () => void;
        },
    ];
    // Emitted when user changes selected domain, with new domain value
    "user-domain-change": [domain: UserType];
    "user-selection-update": [users: SelectedUser[]];
}>();

const auth = useAuth();
const instance = getCurrentInstance();
const dialog = useDialog();
// API service composable for user search to backend.
const { searchUsers, isPending, searchResults, isSuccess, searchError, reset } =
    useUserSearchApiService();

const domainOptions = computed<SelectOption<UserType>[]>(() =>
    (props.availableDomains ?? []).map((domain) => ({
        label: domain === UserType.Idir ? "IDIR" : "BCeID",
        value: domain,
    }))
);

const selectedDomainOption = ref<SelectOption<UserType>>(domainOptions.value[0]);

// Search by: "Username" for BCeID, and "First Name", "Last Name", or "Username" for IDIR
const getSearchTypeOptions = (
    domain: UserType
): SelectOption<UserSearchType>[] => {
    if (domain === UserType.BceidBus) {
        return [{ label: "Username", value: "username" }];
    }

    return [
        { label: "Username", value: "username" },
        { label: "First Name", value: "firstName" },
        { label: "Last Name", value: "lastName" }
    ];
};

const searchTypeOptions = computed<SelectOption<UserSearchType>[]>(() =>
    getSearchTypeOptions(selectedDomainOption.value.value)
);

const selectedSearchTypeOption = ref<SelectOption<UserSearchType>>(
    searchTypeOptions.value[0]
);

const isUsernameSearch = computed(
    () => selectedSearchTypeOption.value.value === "username"
);

/**
 * Test on search text. If contains invalid characters, return error msg.
 * - No space (always).
 * - No numeric (only for firstName/lastName searches).
 */
const getInvalidSearchTextError = (value: string): string => {
    if (/\s/.test(value)) {
        return "Search text cannot contain spaces";
    }

    if (!isUsernameSearch.value && /\d/.test(value)) {
        return "Search text cannot contain numbers";
    }

    return "";
};

const sanitizeSearchText = (value: string): string => {
    if (isUsernameSearch.value) {
        return value.replace(INVALID_SEARCH_TEXT_PATTERN_WITH_DIGITS, "");
    }
    return value.replace(INVALID_SEARCH_TEXT_PATTERN, "");
};

// This validates search text after 'searchText' model update.
const validateSearchText = (): boolean => {
    const trimmed = searchText.value.trim();

    if (!trimmed) {
        searchTextError.value = "Search text is required";
        return false;
    }

    if (trimmed.length > MAX_SEARCH_TEXT_LENGTH) {
        searchTextError.value = `Search text must be ${MAX_SEARCH_TEXT_LENGTH} characters or less`;
        return false;
    }

    const invalidSearchTextError = getInvalidSearchTextError(trimmed);
    if (invalidSearchTextError) {
        searchTextError.value = invalidSearchTextError;
        return false;
    }

    searchTextError.value = "";
    return true;
};

const clearSearchInputState = (isErrorStateOnly = false) => {
    if (isErrorStateOnly) {
        searchTextError.value = "";
        return;
    }
    searchText.value = "";
    searchTextError.value = "";
};

const clearSelectedUsers = () => {
    if (latestConfirmedSelections.value.length === 0) {
        return;
    }

    latestConfirmedSelections.value = [];
    emit("user-selection-update", []);
};

const applyDomainChange = (nextDomainOption: SelectOption<UserType>) => {
    selectedDomainOption.value = nextDomainOption;
    selectedSearchTypeOption.value = getSearchTypeOptions(nextDomainOption.value)[0];
    clearSearchInputState();
    clearSelectedUsers();
    searchResultMessage.value = "";
    reset(); // reset API service state (e.g. clear previous search results and errors)
    emit("user-domain-change", nextDomainOption.value);
};

// 'hasPreDomainChangeListener' is to determine whether parent component listens to "pre-user-domain-change" event.
const hasPreDomainChangeListener = computed(() => {
    const vnodeProps = instance?.vnode.props ?? {};
    // Example parent listens to event: <UserSearch ... @pre-user-domain-change="handlePreDomainChange" />.
    return !!vnodeProps.onPreUserDomainChange;
});

// Note! If parent component does not listen to "pre-user-domain-change", domain change will be applied immediately
// when user selects different domain option. Otherwise, it will wait for parent component's approval
// before applying the change.
const handleDomainSelection = (event: SelectChangeEvent) => {
    const nextDomainOption = event.value as SelectOption<UserType>;
    if (!nextDomainOption || nextDomainOption.value === selectedDomainOption.value.value) {
        return;
    }

    if (!hasPreDomainChangeListener.value) {
        applyDomainChange(nextDomainOption);
        return;
    }

    emit("pre-user-domain-change", {
        currentDomain: selectedDomainOption.value.value,
        nextDomain: nextDomainOption.value,
        selectedUsersCount: latestConfirmedSelections.value.length,
        approveChange: () => applyDomainChange(nextDomainOption),
        cancelChange: () => {
            // PrimeVue v4 Select immediately updates its internal d_value on user
            // selection regardless of whether the parent model changes. Since
            // selectedDomainOption hasn't changed, Vue won't propagate a prop diff
            // and Select's modelValue watcher won't fire to revert the display.
            // Spreading to a new reference forces Vue to detect a change and
            // triggers Select's watcher, resetting d_value back to the old domain.
            // This seems to be PrimeVue bug. See https://github.com/primefaces/primevue/issues/7871
            // and https://github.com/primefaces/primevue/issues/6961
            selectedDomainOption.value = { ...selectedDomainOption.value };
        },
    });
};

const handleSearchTypeChange = (event: SelectChangeEvent) => {
    const nextTypeOption = event.value as SelectOption<UserSearchType>;
    if (!nextTypeOption) {
        return;
    }

    selectedSearchTypeOption.value = nextTypeOption;
    const isErrorStateOnly = true;
    clearSearchInputState(isErrorStateOnly);
    searchResultMessage.value = "";
};

// For search input 'beforeinput' event, to prevent invalid characters from being entered in the first place.
const handleBeforeModelUpdate = (event: InputEvent) => {
    if (!event.data) {
        return;
    }

    const invalidSearchTextError = getInvalidSearchTextError(event.data);
    if (!invalidSearchTextError) {
        return;
    }

    event.preventDefault(); // prevent invalid character from being entered into input
    searchTextError.value = invalidSearchTextError;
};

const handleSearchTextUpdate = (value: string | undefined) => {
    if (typeof value !== "string") {
        return;
    }

    const sanitizedValue = sanitizeSearchText(value);
    if (sanitizedValue !== value) {
        searchTextError.value = getInvalidSearchTextError(value);
        searchText.value = sanitizedValue;
        return;
    }

    searchText.value = value;

    if (searchTextError.value) {
        validateSearchText();
    }
};

const handlePaste = (event: ClipboardEvent) => {
    const pastedText = event.clipboardData?.getData("text") ?? "";
    const invalidSearchTextError = getInvalidSearchTextError(pastedText);
    if (invalidSearchTextError) {
        event.preventDefault();
        searchTextError.value = invalidSearchTextError;
    }
};

// This is to sync selected users from search result dialog to the main state (latestConfirmedSelections).
// Then will notify parent component the updated selected users through "user-selection-update" event.
const syncSelectedUsers = (selectedDataRows: SelectedUser[]) => {
    const currentUsername = (auth.authState.famLoginUser?.username || "").toLowerCase();

    // self is filtered out if among selected users, unless self-selection is allowed.
    const usersExcludingCurrentUser = currentUsername && !props.allowSelfSelection
        ? selectedDataRows.filter(
              (user) => user.userId.toLowerCase() !== currentUsername
          )
        : selectedDataRows;

    if (currentUsername && usersExcludingCurrentUser.length !== selectedDataRows.length) {
        searchResultMessage.value = SELF_SELECTION_ERROR_MSG;
    }

    if (props.multiUserMode) {
        latestConfirmedSelections.value = [
            ...latestConfirmedSelections.value,
            ...usersExcludingCurrentUser,
        ].filter(
            (user, index, self) => {
                // Merging two arrays (latestConfirmedSelections and current selectedDataRows) and removing duplicates based on
                // userId and sourceDomain. Only the first occurrence of each unique user will be kept, later duplicates will be removed.
                return (
                    index ===
                    self.findIndex(
                        (u) =>
                            u.userId.toLowerCase() === user.userId.toLowerCase() &&
                            u.sourceDomain === user.sourceDomain
                    )
                );
            }
        );
    }
    else {
        // Single user mode: only keep the first
        latestConfirmedSelections.value = usersExcludingCurrentUser.slice(0, 1);
    }

    emit("user-selection-update", latestConfirmedSelections.value);
};

const handleDeleteSelectedUser = (userId: string) => {
    latestConfirmedSelections.value = latestConfirmedSelections.value.filter(
        (user) => user.userId.toLowerCase() !== userId.toLowerCase()
    );

    emit("user-selection-update", latestConfirmedSelections.value);
};

const openResultsDialog = (dataRows: SelectedUser[]) => {
    dialog.open(UserSearchResultsDialog, {
        props: {
            modal: true,
            closable: true,
            style: { width: "85vw", "min-width": "52rem" },
        },
        data: {
            rows: dataRows,
            multiUserMode: props.multiUserMode,
        },
        onClose: (options) => {
            const selectedDataRows = options?.data as SelectedUser[] | undefined;
            if (selectedDataRows && selectedDataRows.length > 0) {
                syncSelectedUsers(selectedDataRows);
            }
        },
    });
};

// Watch search results and react after a successful search
watch(isSuccess, (success) => {
    if (!success) return;

    const results = searchResults.value ?? [];
    if (results.length === 0) {
        searchResultMessage.value =
            "No search result found. Check the spelling or try another search.";
    } else {
        searchResultMessage.value = "";
        openResultsDialog(results);
    }
});

// Watch for API errors from the composable
watch(searchError, (err) => {
    if (err) {
        if (err.code === PERMISSION_REQUIRED_FOR_OPERATION) {
            const orgName = auth.authState.famLoginUser?.organization || "Unknown organization";
            searchResultMessage.value = `${err.description ?? err.message}. Org name: ${orgName}`;
            return;
        }

        searchResultMessage.value = err.message;
    }
});

// Triggered when user clicks search button or presses Enter.
const handleSearch = () => {
    if (!validateSearchText()) {
        return;
    }

    // Prevent searching for self when search type is 'username' - cannot grant permission to self,
    // unless self-selection is allowed (e.g. app admin self-granting on dev/test apps).
    if (
        !props.allowSelfSelection &&
        isUsernameSearch.value &&
        searchText.value.trim().toLowerCase() === (auth.authState.famLoginUser?.username || '').toLowerCase()
    ) {
        searchTextError.value = SELF_SELECTION_ERROR_MSG;
        return;
    }

    searchResultMessage.value = "";

    searchUsers({
        domain: selectedDomainOption.value.value,
        searchType: selectedSearchTypeOption.value.value,
        searchText: searchText.value.trim(),
        environment: props.environment,
    });
};
</script>

<template>
    <div class="user-search-container">
        <div class="search-fields-row">
            <Dropdown
                class="field-domain"
                name="user-domain"
                label-text="User domain"
                option-label="label"
                :value="selectedDomainOption"
                :options="domainOptions"
                :on-change="handleDomainSelection"
                :disabled="disabled || domainOptions.length === 1 || isPending"
            />

            <Dropdown
                class="field-type"
                name="search-type"
                label-text="Type"
                option-label="label"
                :value="selectedSearchTypeOption"
                :options="searchTypeOptions"
                :on-change="handleSearchTypeChange"
                :disabled="disabled || isPending"
            />

            <div class="field-search-input">
                <InputText
                    id="user-search-input"
                    :model-value="searchText"
                    @update:model-value="handleSearchTextUpdate"
                    @beforeinput="handleBeforeModelUpdate"
                    @keydown.space.prevent
                    @keydown.enter.prevent="handleSearch"
                    @paste="handlePaste"
                    placeholder="Please input search text"
                    :maxlength="MAX_SEARCH_TEXT_LENGTH"
                    class="w-100"
                    :invalid="!!searchTextError"
                    :disabled="disabled || isPending"
                />
                <HelperText
                     v-if="searchTextError"
                    :text="searchTextError"
                    :is-error="!!searchTextError"
                />
            </div>

            <div class="field-search-button">
                <Button
                    :label="searchButtonLabel"
                    aria-label="Search users"
                    name="searchUsers"
                    outlined
                    :icon="SearchIcon"
                    :disabled="disabled"
                    :is-loading="isPending"
                    @click="handleSearch"
                />
            </div>
        </div>

        <div class="search-error-row">
            <!-- Helper text from parent component -->
            <HelperText
                v-if="helperText !== ''"
                :text="helperText"
            />
            <!-- Internal search result/error message -->
            <HelperText
                v-if="searchResultMessage"
                :text="searchResultMessage"
                :is-error="true"
            />
            <!-- Slot for additional form errors from parent component -->
            <slot name="formError" />
        </div>

        <UserSearchSelectedTable
            v-if="latestConfirmedSelections.length > 0"
            :users="latestConfirmedSelections"
            :multi-user-mode="props.multiUserMode"
            @selected-user-deleted="handleDeleteSelectedUser"
        />
    </div>
</template>

<style lang="scss" scoped>
.user-search-container {
    display: flex;
    flex-direction: column;
}


.search-fields-row {
    display: flex;
    flex-wrap: wrap;
    align-items: flex-start;
    gap: 0.5rem;
}


.field-domain,
.field-type {
    flex: 0 1 10rem;
    min-width: 10.5rem;
    min-height: 2.5rem;
    display: flex;
    flex-direction: column;
    justify-content: flex-end;
}


.field-search-input {
    flex: 1 1 16rem;
    min-width: 12rem;
    min-height: 2.5rem;
    display: flex;
    flex-direction: column;
    justify-content: flex-end;
    margin-top: 1.5rem;
}


.field-search-button {
    flex: 0 0 auto;
    min-height: 2.5rem;
    display: flex;
    align-items: flex-end;
    margin-top: 1.5rem;
    .fam-button {
        width: 7.875rem;
    }
}

.search-error-row {
    width: 100%;
}

</style>
