// frontend/src/components/AddPermissions/ForestClientSelectTable.vue
<script setup lang="ts">
import type { FamForestClientDto } from "fam-api";
import Checkbox from "primevue/checkbox";
import Column from "primevue/column";
import DataTable from "primevue/datatable";
import { Field, useField } from "vee-validate";
import { computed } from "vue";
import Chip from "../UI/Chip.vue";
import ErrorText from "../UI/ErrorText.vue";
import Label from "../UI/Label.vue";
import SubsectionTitle from "../UI/SubsectionTitle.vue";

/**
 * Organisations as a checkbox list, for a caller who may only grant a few.
 *
 * The search box this replaces is the right shape when the answer could be any
 * of tens of thousands of organisations. A delegated administrator's delegation
 * names a handful, and searching for something you have already been told the
 * whole of is work for no reason - you would type, wait, and find the same five
 * rows every time.
 *
 * Deliberately the same shape as the district picker, which has always been a
 * list for the same reason: a fixed, short, known set.
 *
 * <b>Only rendered when restricted.</b> An application administrator may grant
 * any organisation, so their picker stays a search - see ForestClientAddTable.
 */
const props = withDefaults(
    defineProps<{
        /** Form path this picker owns, e.g. `roles[0].forestClients`. */
        fieldId: string;
        selected: FamForestClientDto[];
        /** Exactly the organisations this caller may grant for. */
        options: FamForestClientDto[];
        setFieldValue: (field: string, value: any) => void;
        title?: string;
        subtitle?: string;
    }>(),
    {
        title: "Organizations",
        subtitle: "Select one or more organizations for this role",
    }
);

const { validate: validateClients } = useField(props.fieldId);

const isSelected = (client: FamForestClientDto) =>
    props.selected.some(
        (chosen) => chosen.forest_client_number === client.forest_client_number
    );

const toggle = (client: FamForestClientDto) => {
    const updated = [...props.selected];
    const index = updated.findIndex(
        (chosen) => chosen.forest_client_number === client.forest_client_number
    );

    if (index >= 0) {
        updated.splice(index, 1);
    } else {
        updated.push(client);
    }
    props.setFieldValue(props.fieldId, updated);
    validateClients();
};

/** Nothing to choose: the delegation named none, or none of them is active. */
const nothingToOffer = computed(() => props.options.length === 0);
</script>

<template>
    <div class="forest-client-select-table-container">
        <SubsectionTitle :title="props.title" :subtitle="props.subtitle" />

        <Field
            :name="props.fieldId"
            v-slot="{ errorMessage }"
            :model-value="props.selected"
            @update:model-value="
                (value) => props.setFieldValue(props.fieldId, value)
            "
        >
            <Label label-text="Organizations" required />

            <ErrorText v-if="errorMessage" show-icon :error-msg="errorMessage" />

            <DataTable class="fam-table" :value="props.options">
                <template #empty>
                    <!--
                        Said plainly rather than left blank. An empty table with
                        no explanation reads as a screen that failed to load.
                    -->
                    {{
                        nothingToOffer
                            ? "You have not been delegated any organization for this role"
                            : "No organization available"
                    }}
                </template>

                <Column header="">
                    <template #body="{ data }">
                        <Checkbox
                            class="fam-checkbox"
                            :binary="true"
                            :model-value="isSelected(data)"
                            :aria-label="data.client_name ?? data.forest_client_number"
                            @change="toggle(data)"
                        />
                    </template>
                </Column>

                <Column header="Client number" field="forest_client_number" />

                <Column header="Name">
                    <template #body="{ data }">
                        {{ data.client_name ?? "—" }}
                    </template>
                </Column>

                <Column header="Status">
                    <template #body="{ data }">
                        <Chip
                            v-if="data.status"
                            color="green"
                            :label="data.status.description"
                        />
                    </template>
                </Column>
            </DataTable>
        </Field>
    </div>
</template>

<style lang="scss">
.forest-client-select-table-container {
    .error-text-container {
        padding: 0;
        height: fit-content;
        margin-bottom: 0.5rem;
    }

    .subsection-title-container {
        margin: 1.5rem 0;
    }

    .fam-table {
        .p-datatable-emptymessage {
            background-color: var(--semantic-color-surface-layer-1);
        }
    }

    .fam-checkbox {
        display: flex;
        flex-direction: row;
        align-items: center;

        .p-checkbox-box {
            width: 1rem;
            height: 1rem;
        }
    }
}
</style>

// frontend/src/components/AddPermissions/ForestClientSelectTable.tsx
import {
    Checkbox,
    Table,
    TableBody,
    TableCell,
    TableContainer,
    TableHead,
    TableHeader,
    TableRow,
} from "@carbon/react";
import type { FamForestClientDto } from "fam-api";
import type { FC } from "react";
import { Chip } from "@/components/Chip";
import { PLACE_HOLDER } from "@/constants/constants";
import { SubsectionTitle } from "@/components/SubsectionTitle";
import "./ScopeSelectTable.css";

/**
 * Organisations as a checkbox list, for a caller who may only grant a few.
 *
 * The search box this replaces is the right shape when the answer could be any
 * of tens of thousands of organisations. A delegated administrator's delegation
 * names a handful, and searching for something you have already been told the
 * whole of is work for no reason - you would type, wait, and find the same five
 * rows every time.
 *
 * Deliberately the same shape as the district picker, which has always been a
 * list for the same reason: a fixed, short, known set.
 *
 * <b>Only rendered when restricted.</b> An application administrator may grant
 * any organisation, so their picker stays a search - see ForestClientAddTable.
 */
type Props = {
    selected: FamForestClientDto[];
    /** Exactly the organisations this caller may grant for. */
    options: FamForestClientDto[];
    onChange: (clients: FamForestClientDto[]) => void;
    title?: string;
    subtitle?: string;
    errorMessage?: string;
};

export const ForestClientSelectTable: FC<Props> = ({
    selected,
    options,
    onChange,
    title = "Organizations",
    subtitle = "Select one or more organizations for this role",
    errorMessage,
}) => {
    const toggle = (client: FamForestClientDto) => {
        const index = selected.findIndex(
            (chosen) =>
                chosen.forest_client_number === client.forest_client_number
        );
        onChange(
            index >= 0
                ? selected.filter((_, position) => position !== index)
                : [...selected, client]
        );
    };

    return (
        <div className="scope-select-table-container">
            <SubsectionTitle title={title} subtitle={subtitle} />

            {/*
                A list of checkboxes has no field to mark invalid, so the
                complaint takes Carbon's form-requirement styling by hand -
                the same red line a text field would show, and in the same
                place, without being a notification box.
            */}
            {errorMessage ? (
                <div className="cds--form-requirement" role="alert">
                    {errorMessage}
                </div>
            ) : null}

            <div className="fam-table">
                <TableContainer>
                    <Table size="md" useZebraStyles>
                        <TableHead>
                            <TableRow>
                                <TableHeader aria-label="Select" />
                                <TableHeader>Client number</TableHeader>
                                <TableHeader>Name</TableHeader>
                                <TableHeader>Status</TableHeader>
                            </TableRow>
                        </TableHead>
                        <TableBody>
                            {options.length === 0 ? (
                                <TableRow>
                                    {/*
                                        Said plainly rather than left blank. An
                                        empty table with no explanation reads as
                                        a screen that failed to load.
                                    */}
                                    <TableCell colSpan={4}>
                                        You have not been delegated any
                                        organization for this role
                                    </TableCell>
                                </TableRow>
                            ) : (
                                options.map((client) => (
                                    <TableRow key={client.forest_client_number}>
                                        <TableCell>
                                            <Checkbox
                                                id={`client-${client.forest_client_number}`}
                                                labelText={
                                                    client.client_name ??
                                                    client.forest_client_number
                                                }
                                                hideLabel
                                                checked={selected.some(
                                                    (chosen) =>
                                                        chosen.forest_client_number ===
                                                        client.forest_client_number
                                                )}
                                                onChange={() => toggle(client)}
                                            />
                                        </TableCell>
                                        <TableCell>
                                            {client.forest_client_number}
                                        </TableCell>
                                        <TableCell>
                                            {client.client_name ?? PLACE_HOLDER}
                                        </TableCell>
                                        <TableCell>
                                            {client.status ? (
                                                <Chip
                                                    color="green"
                                                    // Both are optional on
                                                    // the DTO; the code is a
                                                    // poor label but a better
                                                    // one than an empty pill.
                                                    label={
                                                        client.status
                                                            .description ??
                                                        client.status
                                                            .status_code ??
                                                        ""
                                                    }
                                                />
                                            ) : null}
                                        </TableCell>
                                    </TableRow>
                                ))
                            )}
                        </TableBody>
                    </Table>
                </TableContainer>
            </div>
        </div>
    );
};

export default ForestClientSelectTable;
